### ISSUE TITLE
Update the web site to point to new repository

### ISSUE THREAD

**Issue by ColourGrey** [typedclojure/typedclojure.org#1]
The link that one finds on the main page of [Typed Clojure](https://typedclojure.org/), right under the heading "Clojure, with types", points to the old repository. It should probably be updated to point to the new one. Similarly, "Getting Started" points to the wiki in the same old repository.

Furthermore, some of the links on the main page of that site point to documentation from 2013; is documentation this old still relevant to the project?

**Comment by frenchy64** [comment]
Thanks for the issue, moved to the website repo. AFAIK the docs should be stable from 2013, it's mainly the project coordinates that should be updated. Actually, I'd be interested to know any docs that don't work any more.

**Comment by ColourGrey** [comment]
The footer at the very bottom of the page has some problems:
- I would update the copyright year: anyone seeing "© 2013" would rightly believe the project to be dead;
- clicking on either "Privacy" or "Terms" only leads me to the top of the page, nothing else happens. Not good, and it leaves a bad impression.

**Comment by frenchy64** [comment]
> rightly believe the project to be dead

xD RIP

**Comment by frenchy64** [comment]
> Furthermore, some of the links on the main page of that site point to documentation from 2013; is documentation this old still relevant to the project?

If I had more up-to-date docs, I would link to me them. But that's unfortunately not my focus right now--I'll leave this open to prompt me.

**Comment by frenchy64** [comment]
Added https://typedclojure.org/guides/getting_started and linked from the home page. Hard to see if the CDN picked it up, will check tomorrow, but I think that addresses everything, thanks!

**Comment by ColourGrey** [comment]
Let's talk about the header, too! It currently contains three clickable elements: "Typed Clojure", "Home" and "Getting Started".

The first two only take me to typedclojure.org/#, so at least one of them is redundant. But let us look more closely: when is a header useful? When it stays visible all the time. This is not the case on typedclojure.org, though: the header gets out of view as soon as the user begin scrolling down.

Furthermore, the "Getting Started" link appears once more on the main page, on that light blue background - and is much more visible there.

I claim that, with the current organization of the website (a single page containing links to other sites: YouTube, GitHub, Vimeo), the header doesn't serve any purpose. If I were you, I would kill it without regrets.

**Comment by frenchy64** [comment]
My plan is to emulate the navigation on https://clojure.org. Eventually there will be many sections and the header will be much more useful. The `Home` button can probably be removed.
